# Generated by Django 4.2.7 on 2023-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highfives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highfive',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
